### ISSUE TITLE
Create a Git tag to mark the initial release

### ISSUE THREAD

**Issue by Calinou** [19PHOBOSS98/Godot-MirrorInstance#1]
Hi,

I noticed you submitted this asset to the asset library, but the download URL doesn't work as there is no `v1.0` tag in this repository. Please create a tag named `v1.0` to the repository so the download URL will work. You can do this using GitHub's web interface, or locally using `git tag v1.0 -m "Version 1.0"` then `git push --tags`.

**Comment by 19PHOBOSS98** [comment]
Hope that helped :)

**Comment by Calinou** [comment]
Thanks! The asset is now approved: https://godotengine.org/asset-library/asset/491
